# Generated by Django 4.2.1 on 2023-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="raw_password",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Raw Password"
            ),
        ),
    ]
