# Generated by Django 4.2.1 on 2023-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_raw_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="raw_password",
            field=models.CharField(
                blank=True,
                default="password",
                max_length=10,
                null=True,
                verbose_name="Raw Password",
            ),
        ),
    ]
