# Generated by Django 3.2 on 2023-06-20 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("thought", "0002_alter_thought_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thought",
            options={"ordering": ("status", "-activate_date")},
        ),
        migrations.AddField(
            model_name="thought",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thought",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="thought",
            name="is_comment_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="thought",
            name="likes",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="thought",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
